language: python
python:
- 2.7
- 3.2
- 3.3
- 3.4
install:
- sudo apt-get install -y build-essential bc
- pip install -r requirements.txt
- git clone git://github.com/akerl/kernels /tmp/kernel
- mv /tmp/kernel/configs /tmp/configs
- sudo chown -R $USER /boot
script:
- pep8 .
- nosetests --with-coverage --cover-package=roller
after_success:
- coveralls
notifications:
  email: false
  irc:
    channels:
    - irc.oftc.net#akerl
    template:
    - "%{repository}/%{branch}/%{build_number}: %{message} -- %{build_url}"
